#!/usr/bin/env bash

sudo apt install zsh
zsh --version
chsh -s $(which zsh)

sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

git config --global user.email "farhanoktvn@gmail.com"
git config --global user.name "farhanoktvn"

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
